apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  creationTimestamp: null
  name: backend-api.default.svc.cluster.local
  namespace: default
spec:
  routes:
    - condition:
        method: GET
        pathRegex: /
      name: GET /
      timeout: 600s ### ADD THIS LINE ###
      isRetryable: false ### ADD THIS LINE ###
