apiVersion: v1
kind: ServiceAccount
metadata:
  # name: backend-api-account
  # for consul, the name must be the same:
    name: backend-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend-api
    service: backend-api
  name: backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  strategy: {}
  template:
    metadata:
      annotations:
          sidecar.istio.io/proxyCPULimit: "200m"
          sidecar.istio.io/proxyMemoryLimit: "512Mi"
          sidecar.istio.io/inject: "true"
          linkerd.io/inject: "enabled"
          consul.hashicorp.com/consul-sidecar-cpu-limit: "200m"
          consul.hashicorp.com/consul-sidecar-memory-limit: "512Mi"
          consul.hashicorp.com/connect-inject: "true"
          config.linkerd.io/proxy-cpu-limit: '200m'

      creationTimestamp: null
      labels:
        app: backend-api
        version: v1
    spec:
      serviceAccountName: backend-api
      nodeSelector:
        app: service
      containers:
      - image: dahny/backend-api:0.8
    # - image: prj-meshservices-docker.artifactory.svc.elca.ch/backend-api:0.7
        name: backend-api
        resources:
          requests:
            memory: "128Mi"
            cpu: "150m"
          limits:
            memory: "256Mi"
            cpu: "325m"
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: artifactory 
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: backend-api
  name: backend-api
  annotations:
    8080.service.kuma.io/protocol: http
spec:
  ports:
  - name: http-8080 
    port: 8080
    protocol: TCP
    targetPort: 8080
#    nodePort: 30007
  selector:
    app: backend-api
  type: ClusterIP
status:
  loadBalancer: {}
