apiVersion: v1
kind: ServiceAccount
metadata:
    name: counter-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: counter-api
    version: v1
  name: counter-api
spec:
  replicas: 4
  selector:
    matchLabels:
      app: counter-api
  strategy: {}
  template:
    metadata:
      annotations:
          sidecar.istio.io/proxyCPULimit: "200m"
          sidecar.istio.io/proxyMemoryLimit: "512Mi"
          sidecar.istio.io/inject: "true"
          linkerd.io/inject: "enabled"
          consul.hashicorp.com/consul-sidecar-cpu-limit: "200m"
          consul.hashicorp.com/consul-sidecar-memory-limit: "512Mi"
          consul.hashicorp.com/connect-inject: "true"
          config.linkerd.io/proxy-cpu-limit: '200m'
      creationTimestamp: null
      labels:
        app: counter-api
        version: v1
    spec:
      serviceAccountName: counter-api
      nodeSelector:
        app: service
      containers:
      - image: dahny/counter-api:0.5
        name: counter-api
        resources:
          requests:
            memory: "128Mi"
            cpu: "150m"
          limits:
            memory: "256Mi"
            cpu: "325m"
        ports:
        - containerPort: 8081
      imagePullSecrets:
        - name: artifactory
  #  imagePullSecrets:
  #     - name: regcred
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: counter-api
  name: counter-api
  annotations:
    8080.service.kuma.io/protocol: http
spec:
  ports:
  - name: http-8081 
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: counter-api
  type: ClusterIP
status:
  loadBalancer: {}
