global:
  name: consul
  datacenter: dc1
  metrics:
    enabled: true
    enableAgentMetrics: false
server:
  replicas: 1
  securityContext:
    runAsNonRoot: false
    runAsUser: 0
connectInject:
  enabled: true
controller:
  enabled: true
ui:
  enabled: true
#prometheus:
#  enabled: true
#grafana:
#  enabled: true
